import styles from "./MainLayout.module.css";
import Head from "next/head";
import {NavBar} from "../NavBar";
import Link from "next/link";
import {FC} from "react";


// @ts-ignore
export const MainLayout: FC = ({children}) =>{
    return (
        <div className={styles.content}>
            <Head>
                <title>Home - LimberApp</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar/>

            <main className={`${styles.main}`}>

                {children}

            </main>
        </div>
    )
}
